apiVersion: v1
kind: Namespace
metadata:
  name: myimage
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: artifactory.oneeuronet.com/oen-oneeuronet-images/myimage:red
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myimage-svc
spec:
  selector:
    app: myimage
  ports:
  - port: 80
    targetPort: 80
